version: "3"
services:
        vlc:
                image: boydachina/vlc-server
                ports: 
                        - 8080:8080
                        - 8080:8080/udp
                        - 8554:8554/udp
                        - 8554:8554
                networks:
                        - vlc_net
                command:
                        #- cvlc -vvv /opt/vlc-media/python.mp4 --sout '#rtp{sdp=rtsp://:8554/}'
                        #- cvlc -vvv /opt/vlc-media/python.mp4 --sout '#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100}:rtp{sdp=rtsp://:8080/}'        
                        - cvlc -vvv /opt/vlc-media/python.mp4 --sout '#transcode{vcodec=mp4v,acodec=mpga,vb=4096,ab=128}:standard{access=http,mux=ogg,dst=:8080}' 
                volumes:
                        - ./media:/opt/vlc-media/ # o caminho onde está os arquivos de video
networks:
        vlc_net:
